FROM alpine:3.22.1

# ---------- Update System and install necessary Software --------------------------------------------------------------

# Setup Scripts https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-timezone

RUN apk update; \
    apk upgrade; \
    apk add openjdk21-jre openjdk21-jmods; \
    apk add font-misc-misc fontconfig ttf-dejavu; \
    fc-cache --force; \
    apk add alpine-conf; \
    setup-timezone -z Europe/Berlin; \
    rm -rf /var/cache/apk/*

# ---------- Configure Java --------------------------------------------------------------------------------------------

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME=/usr/lib/jvm/default-jvm

# ---------- Abschluss der Konfiguration -------------------------------------------------------------------------------

ENV LANGUAGE='de_DE:de'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

USER 185

# Log und SSL Verzeichnis anlegen
RUN mkdir /deployments/logs &&  mkdir /deployments/ssl

# Workdir festlegen
WORKDIR /deployments

EXPOSE 8080 8443

# Zusätzliche Quarkus-spezifische Java-Optionen
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

# Direkter Start von Quarkus über "java -jar ..."
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS $JAVA_OPTS_APPEND -jar /deployments/quarkus-run.jar"]
